import { describe, it, expect } from "vitest";
import {
  parsePly,
  parsePlyAscii,
  parseXyz,
  ingestPointCloudToPoses,
  __test__,
  type PartLineDef,
} from "../pipelines/pointcloudIngest.js";
import { generateSyntheticLinePoints, type ScanPoint } from "../core/scan/index.js";
import { generateDirectives } from "../core/generateDirectives.js";
import type {
  ConstraintsDataset,
  NominalPosesDataset,
} from "../core/types.js";

function serializeToPlyAscii(points: ScanPoint[]): string {
  const header = [
    "ply",
    "format ascii 1.0",
    "comment generated by pointcloud.ingest.test",
    `element vertex ${points.length}`,
    "property float x",
    "property float y",
    "property float z",
    "end_header",
  ].join("\n");
  const body = points.map((p) => `${p.point_mm[0]} ${p.point_mm[1]} ${p.point_mm[2]}`).join("\n");
  return `${header}\n${body}\n`;
}

describe("point-cloud parsers", () => {
  it("parsePlyAscii round-trips a 3-vertex ASCII PLY", () => {
    const text = [
      "ply",
      "format ascii 1.0",
      "comment minimal fixture",
      "element vertex 3",
      "property float x",
      "property float y",
      "property float z",
      "property float intensity",
      "end_header",
      "1.0 2.0 3.0 0.5",
      "4.5 -5.5 6.25 0.9",
      "0 0 0 1.0",
    ].join("\n");

    const pts = parsePlyAscii(text);
    expect(pts).toHaveLength(3);
    expect(pts[0].point_mm[0]).toBeCloseTo(1.0, 6);
    expect(pts[0].point_mm[1]).toBeCloseTo(2.0, 6);
    expect(pts[0].point_mm[2]).toBeCloseTo(3.0, 6);
    expect(pts[0].intensity).toBeCloseTo(0.5, 6);
    expect(pts[1].point_mm).toEqual([4.5, -5.5, 6.25]);
    expect(pts[2].intensity).toBeCloseTo(1.0, 6);
  });

  it("parseXyz skips comments and blank lines and reads optional intensity", () => {
    const text = [
      "# leading comment",
      "",
      "1.0 2.0 3.0",
      "  4.5   -5.5  6.25  0.75",
      "",
      "# another comment",
      "0 0 0",
    ].join("\n");

    const pts = parseXyz(text);
    expect(pts).toHaveLength(3);
    expect(pts[0].point_mm).toEqual([1.0, 2.0, 3.0]);
    expect(pts[0].intensity).toBeUndefined();
    expect(pts[1].point_mm).toEqual([4.5, -5.5, 6.25]);
    expect(pts[1].intensity).toBeCloseTo(0.75, 6);
    expect(pts[2].point_mm).toEqual([0, 0, 0]);
  });

  it("parsePly rejects ArrayBuffer input with the binary-not-supported message", () => {
    expect(() => parsePly(new ArrayBuffer(8))).toThrow(/binary PLY not yet supported/);
  });

  it("parsePlyAscii rejects a malformed header (missing magic)", () => {
    const text = "format ascii 1.0\nelement vertex 0\nend_header\n";
    expect(() => parsePlyAscii(text)).toThrow(/malformed PLY/);
  });
});

describe("ingestPointCloudToPoses end-to-end (toy_facade P-05 stand-in)", () => {
  it("recovers a translate ≈ [-6.5, 1, 0] mm and emits a rotate_to_index directive for P-05", () => {
    // Nominal mullion: 1m vertical line centered at world origin.
    const nominalP0: [number, number, number] = [0, -500, 0];
    const nominalP1: [number, number, number] = [0, 500, 0];

    // Ground-truth as-built line: shifted +6.5mm in X, -1mm in Y.
    // (The MVP poseFromLineFit returns identity rotation, so the 3°
    // rotation is carried in the *nominal* pose rather than baked into
    // the synthetic points — it still drives the rotate_to_index path.)
    const asBuiltP0: [number, number, number] = [6.5, -501, 0];
    const asBuiltP1: [number, number, number] = [6.5, 499, 0];

    const truePoints = generateSyntheticLinePoints(asBuiltP0, asBuiltP1, {
      num_points: 200,
      noise_perpendicular_mm: 1,
      noise_along_mm: 0.3,
      seed: 12345,
    });

    const ply = serializeToPlyAscii(truePoints);
    const parsed = parsePly(ply);
    expect(parsed.length).toBe(truePoints.length);

    const partLines: PartLineDef[] = [
      { partId: "P-05", p0Nominal: nominalP0, p1Nominal: nominalP1 },
    ];

    const asBuilt = ingestPointCloudToPoses({ points: parsed, partLines });
    expect(asBuilt.parts).toHaveLength(1);
    const recovered = asBuilt.parts[0];
    expect(recovered.part_id).toBe("P-05");
    expect(recovered.pose_confidence).toBeGreaterThan(0.5);

    // Nominal carries the 3° rotation about Y so the engine sees a
    // rotation error and emits the rotate_to_index directive.
    const halfAngleRad = (3 * Math.PI) / 180 / 2;
    const yQuatY = Math.sin(halfAngleRad);
    const yQuatW = Math.cos(halfAngleRad);
    const nominal: NominalPosesDataset = {
      schema_version: "v0.1",
      dataset_id: "toy_facade_v1_nominal",
      frame_id: "world",
      units: { length: "mm", rotation: "quaternion_xyzw" },
      parts: [
        {
          part_id: "P-05",
          part_name: "P-05",
          part_type: "panel",
          T_world_part_nominal: {
            translation_mm: [0, 0, 0],
            rotation_quat_xyzw: [0, yQuatY, 0, yQuatW],
          },
        },
      ],
    };

    const constraints: ConstraintsDataset = {
      schema_version: "v0.1",
      dataset_id: "toy_facade_v1_constraints",
      engine_config: { confidence_threshold: 0.5 },
      parts: [
        {
          part_id: "P-05",
          allowed_translation_axes: { x: true, y: true, z: true },
          rotation_mode: "index",
          allowed_rotation_axes: { x: false, y: true, z: false },
          index_rotation: {
            axis: "y",
            increment_deg: 3,
            allowed_indices: [0],
            nominal_index: 0,
          },
          tolerances: { translation_mm: 2, rotation_deg: 0.5 },
        },
      ],
    };

    const directives = generateDirectives({ nominal, asBuilt, constraints });
    expect(directives.steps).toHaveLength(1);
    const step = directives.steps[0];

    const translateAction = step.actions.find((a) => a.type === "translate");
    expect(translateAction).toBeDefined();
    const t = translateAction!.delta!.translation_mm;
    expect(t[0]).toBeCloseTo(-6.5, 0); // ±0.5mm tolerance
    expect(Math.abs(t[0] - -6.5)).toBeLessThanOrEqual(0.5);
    expect(Math.abs(t[1] - 1)).toBeLessThanOrEqual(0.5);
    expect(Math.abs(t[2] - 0)).toBeLessThanOrEqual(0.5);

    const rotateIndexAction = step.actions.find((a) => a.type === "rotate_to_index");
    expect(rotateIndexAction).toBeDefined();
    expect(rotateIndexAction!.target_index).toBe(0);
    expect(rotateIndexAction!.axis).toBe("y");
  });
});

describe("runIngest (CLI core path)", () => {
  it("produces an AsBuiltPosesDataset matching the schema for in-memory points", () => {
    const points: ScanPoint[] = generateSyntheticLinePoints([0, 0, 0], [0, 1000, 0], {
      num_points: 80,
      noise_perpendicular_mm: 1,
      noise_along_mm: 0.3,
      seed: 7,
    });

    const partLines: PartLineDef[] = [
      { partId: "PART-A", p0Nominal: [0, 0, 0], p1Nominal: [0, 1000, 0] },
    ];

    const result = __test__.runIngest(
      points,
      partLines,
      { translation_mm: [0, 0, 0], rotation_quat_xyzw: [0, 0, 0, 1] },
      {
        anchor_rms_threshold_mm: 5,
        tube_radius_mm: 35,
        synthetic_points_per_part: 100,
        synthetic_noise_mm: 3,
        verification_tolerance_mm: 5,
      }
    );

    expect(result.schema_version).toBe("v0.1");
    expect(result.frame_id).toBe("world");
    expect(result.units.length).toBe("mm");
    expect(result.units.rotation).toBe("quaternion_xyzw");
    expect(typeof result.measured_at).toBe("string");
    expect(Date.parse(result.measured_at)).not.toBeNaN();
    expect(result.parts).toHaveLength(1);

    const part = result.parts[0];
    expect(part.part_id).toBe("PART-A");
    expect(part.T_world_part_asBuilt.translation_mm).toHaveLength(3);
    expect(part.T_world_part_asBuilt.rotation_quat_xyzw).toHaveLength(4);
    expect(part.pose_confidence).toBeGreaterThan(0);
    expect(part.pose_confidence).toBeLessThanOrEqual(1);
    expect(typeof part.confidence_notes).toBe("string");

    // Centroid should sit near the midpoint of the line (within noise).
    expect(Math.abs(part.T_world_part_asBuilt.translation_mm[1] - 500)).toBeLessThan(10);
  });
});
